apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ikh7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-ikh7@sha256:bde9c8e2a5e1d50680bfd0f47b4771dba89b6452de295919fef1da0bc6f04849
        name: my-nodejs
        resources: {}
status: {}
